# Assessments
YW
* write a function to find the mean of a list of numbers
* write a function that calculates a dot product
* write a function that centers an array on the mean 
* write a function to calculate the standard deviation of a list of a numbers (preferably using a dot product)
* write a function to calculate the correlation and covariance of two lists
* write a function to calculate the cost between ytrue and ypred

In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [6]:
def mean_center(lst1):
    """
    write a function that takes in a list
    and returns that list but centered on the mean
    
    in other words x -> (x - mu)
    """
    return lst1 - np.mean(lst1)


def dot_product(lst1, lst2):
    """
    write a function that takes in a list 
    of numbers and returns their dot product
    """
    if len(lst1)!=len(lst2):
        raise Exception("Vector lengths are not equal!")
        return None
    s = 0
    for i in range(len(lst1)):
        p = lst1[i]*lst2[i]
        s+=p
    return s        

In [19]:
# Checking to make sure the function works
lst1 = [1,2,3,4,5]
print(mean_center(lst1))
# Checking the dot product function
lst2 = [6,7,8,9,10]
print(dot_product(lst1, lst2))
np.dot(lst1, lst2)

[-2. -1.  0.  1.  2.]
130


130

# Standard Deviation Formula
![](images/standard-deviation.png)

In [8]:
def standard_deviation(lst1):
    """
    write a function that takes in a list
    of numbers and returns its standard deviation
    """
    mean_center_lst1 = mean_center(lst1)
    numerator = dot_product(mean_center_lst1, mean_center_lst1)
    denominator = len(lst1)
    return np.sqrt(numerator / denominator)

In [20]:
# Checking the standard_deviation function
print(standard_deviation(lst1))
# Checking with numpy
np.std(lst1)

1.4142135623730951


1.4142135623730951

# Covariance Formula
![](images/covariance.png)

In [10]:
def covariance(lst1, lst2):
    """
    write an function that takes in two lists
    of numbers and returns their covariance
    """
    lst1_mean = mean_center(lst1) 
    lst2_mean = mean_center(lst2) 
    numerator = dot_product(lst1_mean, lst2_mean)
    denominator = len(lst1)
    return numerator / denominator

In [21]:
# Checking the covariance function
print(covariance(lst1, lst2))
# Checking with numpy
np.cov(lst1, lst2)

2.0


array([[2.5, 2.5],
       [2.5, 2.5]])

# Correlation Formula
![](images/correlation.png)

In [12]:
def correlation(lst1, lst2):
    """
    write an function that takes in two lists 
    of numbers and returns their correlation
    """
    lst1_mean = mean_center(lst1)
    lst2_mean = mean_center(lst2)
    numerator = dot_product(lst1_mean, lst2_mean)
    denominator = np.sqrt(dot_product(lst1_mean, lst1_mean) * dot_product(lst2_mean, lst2_mean))
    return numerator / denominator

In [22]:
# Checking the correlation function
print(correlation(lst1, lst2))
# Checking with numpy function to make sure it worked
np.corrcoef(lst1, lst2)

1.0


array([[1., 1.],
       [1., 1.]])

# RMSE Formula
![](images/rmse.png)

In [14]:
def rmse(ytrue, ypred):
    """
    write a function that takes in ytrue and ypred
    and returns their root mean squared error
    """
    centered = ypred - ytrue
    numerator = dot_product(centered, centered)
    denominator = len(ytrue)
    return np.sqrt(numerator / denominator)

In [16]:
# Checking to make sure the RMSE function works
print(rmse(lst1, lst2))
# Checking with the numpy RMSE function as well
np.sqrt(mean_squared_error(lst1, lst2))

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# RSS Formula 
![](images/rss.png)

In [17]:
def rss(ytrue, ypred):
    """
    write a function that takes in ytrue and ypred
    and returns their rss
    """
    centered = ytrue - ypred
    return dot_product(centered, centered)

In [18]:
# Checking the RSS function above
print(rss(lst1, lst2))
# Checking against the mean_squared_error function
mean_squared_error(lst1, lst2) * len(lst1)

TypeError: unsupported operand type(s) for -: 'list' and 'list'